using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CompiladorMorse.App.transversal
{
    public enum CategoriaGramatical
    {
        SIMBOLO, FIN_ARCHIVO, FIN_LINEA, ERROR, ERROR_CRITICO, 
        SIMBOLO_MORSE_A, SIMBOLO_MORSE_B, SIMBOLO_MORSE_C, SIMBOLO_MORSE_D, SIMBOLO_MORSE_E, SIMBOLO_MORSE_F, SIMBOLO_MORSE_G, SIMBOLO_MORSE_H,
        SIMBOLO_MORSE_I, SIMBOLO_MORSE_J, SIMBOLO_MORSE_K, SIMBOLO_MORSE_L, SIMBOLO_MORSE_M, SIMBOLO_MORSE_N, SIMBOLO_MORSE_O,
        SIMBOLO_MORSE_P, SIMBOLO_MORSE_Q, SIMBOLO_MORSE_R, SIMBOLO_MORSE_S, SIMBOLO_MORSE_T, SIMBOLO_MORSE_U, SIMBOLO_MORSE_V,
        SIMBOLO_MORSE_W, SIMBOLO_MORSE_X, SIMBOLO_MORSE_Y, SIMBOLO_MORSE_Z,
        SIMBOLO_MORSE_1, SIMBOLO_MORSE_2, SIMBOLO_MORSE_3,SIMBOLO_MORSE_4,SIMBOLO_MORSE_5, SIMBOLO_MORSE_6, SIMBOLO_MORSE_7,
        SIMBOLO_MORSE_8, SIMBOLO_MORSE_9, SIMBOLO_MORSE_0,
        SIMBOLO_COMA, SIMBOLO_DOS_PUNTOS, SIMBOLO_GUION, SIMBOLO_PARENTESIS, SIMBOLO_COMILLAS,SIMBOLO_PUNTO
    }
}
